name: Build, Push and Deploy Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin' 
        java-version: '17'

    - name: Build the Jar file
      run: |
        chmod +x ./mvnw
        ./mvnw clean package -DskipTests

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set image tag
      id: vars
      run: echo "TAG=${GTIHUB_SHA::7}" >> $GITHUB_OUTPUT

    - name: Build the Docker image (SHA + latest)
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-ci-demo:${{ steps.vars.outputs.TAG }} -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-ci-demo:latest .

    - name: Push the images (SHA + latest)
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-ci-demo:${{ steps.vars.outputs.TAG }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-ci-demo:latest

    - name: SSH and deploy to AWS EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e
          TAG=${{ steps.vars.outputs.TAG }}
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/springboot-ci-demo:$TAG
          docker pull $IMAGE
          docker stop spring-demo || true
          docker rm spring-demo || true
          docker run -d --restart unless-stopped --name spring-demo -p 8080:8080 $IMAGE
          docker ps